# Generated by Django 4.2.2 on 2023-07-15 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mbk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportivefact',
            name='reference',
            field=models.CharField(choices=[('Al-Fatiha', 'الفاتحه'), ('Al-Baqarah', 'البقره'), ('Aali Imran', 'آل عمران'), ('An-Nisa', 'النساء'), ("Al-Ma'idah", 'المائده'), ("Al-An'am", 'الأنعام'), ("Al-A'raf", 'الأعراف'), ('Al-Anfal', 'الأنفال'), ('At-Tawbah', 'التوبة'), ('Yunus', 'يونس'), ('Hud', 'هود'), ('Yusuf', 'يوسف'), ("Ar-Ra'd", 'الرعد'), ('Ibrahim', 'ابراهيم'), ('Al-Hijr', 'الحجر'), ('An-Nahl', 'النحل'), ('Al-Isra', 'الإسراء'), ('Al-Kahf', 'الكهف'), ('Maryam', 'مريم'), ('Ta-Ha', 'طه'), ('Al-Anbiya', 'الأنبياء'), ('Al-Hajj', 'الحج'), ("Al-Mu'minun", 'المؤمنون'), ('An-Nur', 'النور'), ('Al-Furqan', 'الفرقان'), ("Ash-Shu'ara", 'الشعراء'), ('An-Naml', 'النمل'), ('Al-Qasas', 'القصص'), ('Al-Ankabut', 'العنكبوت'), ('Ar-Rum', 'الروم'), ('Luqman', 'لقمان'), ('As-Sajda', 'السجدة'), ('Al-Ahzab', 'الأحزاب'), ('Saba', 'سبأ'), ('Fatir', 'فاطر'), ('Ya-Sin', 'يس'), ('As-Saffat', 'الصافات'), ('Sad', 'ص'), ('Az-Zumar', 'الزمر'), ('Ghafir', 'غافر'), ('Fussilat', 'فصلت'), ('Ash-Shura', 'الشورى'), ('Az-Zukhruf', 'الزخرف'), ('Ad-Dukhan', 'الدخان'), ('Al-Jathiyah', 'الجاثية'), ('Al-Ahqaf', 'الأحقاف'), ('Muhammad', 'محمد'), ('Al-Fath', 'الفتح'), ('Al-Hujurat', 'الحجرات'), ('Qaf', 'ق'), ('Adh-Dhariyat', 'الذاريات'), ('At-Tur', 'الطور'), ('An-Najm', 'النجم'), ('Al-Qamar', 'القمر'), ('Ar-Rahman', 'الرحمن'), ("Al-Waqi'a", 'الواقعة'), ('Al-Hadid', 'الحديد'), ('Al-Mujadila', 'المجادلة'), ('Al-Hashr', 'الحشر'), ('Al-Mumtahanah', 'الممتحنة'), ('As-Saff', 'الصف'), ("Al-Jumu'ah", 'الجمعة'), ('Al-Munafiqun', 'المنافقون'), ('At-Taghabun', 'التغابن'), ('At-Talaq', 'الطلاق'), ('At-Tahrim', 'التحريم'), ('Al-Mulk', 'الملك'), ('Al-Qalam', 'القلم'), ('Al-Haqqah', 'الحاقة'), ("Al-Ma'arij", 'المعارج'), ('Nuh', 'نوح'), ('Al-Jinn', 'الجن'), ('Al-Muzzammil', 'المزمل'), ('Al-Muddathir', 'المدثر'), ('Al-Qiyamah', 'القيامة'), ('Al-Insan', 'الإنسان'), ('Al-Mursalat', 'المرسلات'), ('An-Naba', 'النبإ'), ("An-Nazi'at", 'النازعات'), ('Abasa', 'عبس'), ('At-Takwir', 'التكوير'), ('Al-Infitar', 'الإنفطار'), ('Al-Mutaffifin', 'المطففين'), ('Al-Inshiqaq', 'الإنشقاق'), ('Al-Buruj', 'البروج'), ('At-Tariq', 'الطارق'), ("Al-A'la", 'الأعلى'), ('Al-Ghashiyah', 'الغاشية'), ('Al-Fajr', 'الفجر'), ('Al-Balad', 'البلد'), ('Ash-Shams', 'الشمس'), ('Al-Lail', 'الليل'), ('Ad-Duha', 'الضحى'), ('Ash-Sharh', 'الشرح'), ('At-Tin', 'التين'), ('Al-Alaq', 'العلق'), ('Al-Qadr', 'القدر'), ('Al-Bayyinah', 'البينة'), ('Az-Zalzalah', 'الزلزلة'), ('Al-Adiyat', 'العاديات'), ('Al-Qariah', 'القارعة'), ('At-Takathur', 'التكاثر'), ('Al-Asr', 'العصر'), ('Al-Humazah', 'الهمزة'), ('Al-Fil', 'الفيل'), ('Quraish', 'قريش'), ("Al-Ma'un", 'الماعون'), ('Al-Kawthar', 'الكوثر'), ('Al-Kafirun', 'الكافرون'), ('An-Nasr', 'النصر'), ('Al-Masad', 'المسد'), ('Al-Ikhlas', 'الإخلاص'), ('Al-Falaq', 'الفلق'), ('An-Nas', 'الناس')], default='', max_length=15),
        ),
        migrations.AddField(
            model_name='supportivefact',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
