# Generated by Django 4.2.2 on 2023-07-15 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbk', '0002_supportivefact_reference_supportivefact_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theory',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='theory',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='theory',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
