# Generated by Django 4.2.2 on 2023-07-15 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbk', '0003_remove_theory_created_at_remove_theory_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theory',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
