# Generated by Django 4.2.2 on 2023-07-18 20:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mbk', '0004_alter_theory_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportivefact',
            name='reference',
        ),
        migrations.RemoveField(
            model_name='supportivefact',
            name='user',
        ),
        migrations.RemoveField(
            model_name='theory',
            name='active',
        ),
        migrations.AddField(
            model_name='theory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='theory',
            name='description',
            field=models.TextField(),
        ),
    ]
