name: github Deploy
run-name: ${{ github.actor }} let's deploy on server
on: [ push]
jobs:
  Deploy-on-ec2:
    runs-on: ubuntu-22.04
    name: Deploy
    steps:
      - name: deploy to ec2 instance
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: 34.244.85.128
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          port: 22
          debug: true
          script: |
            cd webDict
            git pull origin master
            docker build . -t web-dict
            docker run -ti -d -p 80:8080 web-dict