name: github Deploy
run-name: ${{ github.actor }} let's deploy on server
on: [ push]
jobs:
  Deploy-on-ec2:
    runs-on: ubuntu-18.04
    name: Deploy
    steps:
      - name: deploy to ec2 instance
        uses: appleboy/ssh-action@master
        with:
          host: 34.244.85.128
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          port: 22
          script: |
            cd webDict
            git pull origin master
            git status
            ls -la