name: github Deploy
run-name: ${{ github.actor }} let's deploy on server
on: [ push]
jobs:
  Deploy-on-ec2:
    runs-on: ubuntu-22.04
    name: Deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: deploy to ec2 instance
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: 54.194.46.28
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          port: 22
          debug: true
          script: |
            if [ -d "webDict" ]; then
              echo "Directory webDict exist."
              rm -rf webDict
            fi
            git clone --branch feat/workflow https://github.com/millad90s/webDict.git
            cd webDict
            docker build . -t web-dict
            docker stop webdict | true
            docker rm webdict | true
            docker run -ti -d --name webdict -p 80:8080 web-dict
